# proyecto/docker-compose.yml
version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodata:/home/dynamodblocal/data

  node-express:
    build:
      context: .
      dockerfile: infrastructure/node/Dockerfile      
    container_name: node-express
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    depends_on:
      - dynamodb
    environment:
      NODE_ENV: ${NODE_ENV}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_API_VERSION: ${AWS_API_VERSION}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_CLOCK_TOLERANCE: ${JWT_CLOCK_TOLERANCE}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_COMPLETE: ${JWT_COMPLETE}
      JWT_IGNORE_EXPIRATION: ${JWT_IGNORE_EXPIRATION}
      JWT_IGNORE_NOT_BEFORE: ${JWT_IGNORE_NOT_BEFORE}
      WEBHOOK_URL: ${WEBHOOK_URL}
      PORT: ${PORT}
      API_PREFIX: ${API_PREFIX}

volumes:
  dynamodata:
