### Install VSCode extension Rest Client
### @link https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###################################################
### Get all transactions without jwt
GET http://localhost:3000/api/transaction

### Get transaction by id A108 without jwt
GET http://localhost:3000/api/transaction/A108

### Get Token
GET http://localhost:3000/api/auth/login

### Get all transactions with jwt
GET http://localhost:3000/api/transaction/security
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJwZXBpdG8gZ29uemFsZXoiLCJ1c2VybmFtZSI6InBlcC5nb256Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzE4MjQxMzgzLCJleHAiOjE3MTgyNDQ5ODMsImF1ZCI6IkFVRElFTkNFIiwiaXNzIjoiSVNTVUVSIn0.Ur8xvrXeCLb3vHu22tXNVRA-fXwa1W5mFueS2kQ4fKs

###################################################
### Request body json to hashed token and get config jwt
POST http://localhost:3000/api/jwt/sign-body-request-to-hash-token
Content-Type: application/json

{
    "id_alianza": "alianza",
    "codigo_respuesta": "Estado",
    "resultado": "OK o NOK",
    "fecha": "2024-05-27T15:30:00Z",
    "monto": 1500,
    "monto_propina": 200,
    "medio_de_pago": 1,
    "transactionId": "txn-00123456789",
    "marca": "V",
    "ultimos_digitos_tarjeta": 1234,
    "tipo_tarjeta": "crédito", 
    "cuotas": 3,
    "n_serie": "POS123456789",
    "oc_alianza": "alianza1234567890",
    "rrn": "123456"
}

### Request body hashed to hashed token and get config jwt
POST http://localhost:3000/api/jwt/verify-hashed-body-request-check
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hbGlhbnphIjoiYWxpYW56YSIsImNvZGlnb19yZXNwdWVzdGEiOiJFc3RhZG8iLCJyZXN1bHRhZG8iOiJPSyBvIE5PSyIsImZlY2hhIjoiMjAyNC0wNS0yN1QxNTozMDowMFoiLCJtb250byI6MTUwMCwibW9udG9fcHJvcGluYSI6MjAwLCJtZWRpb19kZV9wYWdvIjoxLCJ0cmFuc2FjdGlvbklkIjoidHhuLTAwMTIzNDU2Nzg5IiwibWFyY2EiOiJWIiwidWx0aW1vc19kaWdpdG9zX3RhcmpldGEiOjEyMzQsInRpcG9fdGFyamV0YSI6ImNyw6lkaXRvIiwiY3VvdGFzIjozLCJuX3NlcmllIjoiUE9TMTIzNDU2Nzg5Iiwib2NfYWxpYW56YSI6ImFsaWFuemExMjM0NTY3ODkwIiwicnJuIjoiMTIzNDU2IiwiaWF0IjoxNzE4MjQ4NjgzLCJleHAiOjE3MTgyNTIyODMsImF1ZCI6IkFVRElFTkNFIiwiaXNzIjoiSVNTVUVSIn0.k4o98L1AR0mBKr7TxU5AgGXxU9VdpSjMtFvsZ44CTOY"
}
